config/routes.rb
Rails.application.routes.draw do
  resources :clothes
  resources :users
  resources :carts
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "login#new"
  post "/login", to: "login#verify"
  delete '/login', to: "login#destroy", as: "logout"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart< ApplicationRecord
    belongs_to :user
    belongs_to :clothe
end

app/models/clothe.rb
class Clothe < ApplicationRecord
    has_many :carts, dependent: :destroy
    has_many :users, through: :carts
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :carts, dependent: :destroy
    has_many :clothes, through: :carts
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
        if session[:user_id]
        @user = User.find(session[:user_id])
        end
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def create
        @cart = Cart.new(strong_params)
        @cart.user_id = current_user.id
        @cart.save
        redirect_to clothes_path
    end

    # def show
    #     @cart = Cart.find(params[:id])
    # end
    
    def destroy 
       @cart = Cart.find(params[:clothe][:cart_id])
       @cart.destroy
       redirect_to user_path(params[:id])
    end

        
    private
    def strong_params
        params.require(:cart).permit(:clothe_id)
    end

end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

    def index 
        if session[:user_id]
        @clothes = Clothe.all 
        else 
            redirect_to login_path
        end
    end

    def show
        if session[:user_id]
        @clothe = Clothe.find(params[:id])
        else 
        redirect_to login_path
        end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController


#similar to our create (takes data from login page and verifies data)
    def verify
        @user = User.find_by(username: params[:login][:username])
        @user = @user.try(:authenticate, params[:login][:password])


        if @user 
            session[:user_id] = @user.id
            redirect_to clothes_path
        else
            flash[:message] = "Incorrect Details!"
            render :new
        end
    end

    def destroy
        # User.find(session[:user_id]).destroy      
        session[:user_id] = nil         
        redirect_to '/login' 
    end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to login_path
        else
            render :new
        end
    end
    
    def show
        if session[:user_id]
            @user = User.find(current_user.id)
        else
            redirect_to to login_path
        end
    end

    def edit
        @user = User.find(current_user.id)
    end

    def update
        @user = User.find(current_user.id)
        @user.update(user_params)
        redirect_to user_path(current_user.id)
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :favorite_style)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clothes/index.html.erb
<h1> All Clothes </h1>
<h1><%= link_to "MY CART & PROFILE", user_path(current_user) %></h1> 
<% @clothes.each do |clothe| %>
        <h1><%= link_to clothe.name, clothe %></h1>
<% end %>

app/views/clothes/show.html.erb
<h1><%= @clothe.name %></h1>
<h1><%= link_to "MY CART", user_path(current_user) %></h1>
Apparel: <%= @clothe.apparel %><br>
Style: <%= @clothe.style %><br>
Price: <%= @clothe.price %><br>
<%= form_for Cart.new, url: carts_path, method: :post do |f| %>
    <%= f.hidden_field :clothe_id, value: @clothe.id %>    
    <%= f.submit "Add to Cart" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ESRNSWEBAPP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<%= form_for :login do |f| %>
    Username: <%= f.text_field :username %>
    Password: <%= f.password_field :password %>
    <%= f.submit "Login" %>
    <% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    Email: <%= f.text_field :email %><br><br>
    What Embodies Your Current Style? <%= f.select :favorite_style, ['City Wear', 'Vintage', 'Gala', 'Surfer', 'Skater']%>
    <%= f.submit "Submit Edit" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
Username: <%= f.text_field :username %><br><br>
Password: <%= f.password_field :password %>
Email: <%= f.text_field :email %><br><br>
What Embodies Your Current Style? <%= f.select :favorite_style, ['City-wear', 'Vintage', 'Gala', 'Surfer', 'Skater']%>

<%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1> My Cart </h1>
<h1>Username: <%= @user.username %></h1>
<h1>Email: <%= @user.email %><br></h1>
<h1>Your Favorite Style: <%= @user.favorite_style %></h1>

<%= link_to "Edit Profile", edit_user_path(@user) %>

<% @user.carts.each do |cart| %>
    <h2><%= cart.clothe.name %></h1>
Apparel: <%= cart.clothe.apparel %><br>
Style: <%= cart.clothe.style %><br>
Price: <%= cart.clothe.price %><br>
<%= form_for cart.clothe, url: cart_path, method: :delete do |f| %>
    <%= f.hidden_field :clothe_id, value: cart.clothe.id %> 
    <%= f.hidden_field :cart_id, value: cart.id %> 

    <%= f.submit "Delete Item" %>
<% end %>
<% end %>
<%= button_to 'Logout', logout_path, :method => :delete %>